version: "3.7"
services:

  api:
    build:
      dockerfile: Dockerfile
      context: .
    command: "./bin/api"
    environment:
      - KAFKA_BROKERS=kafka:9092
    ports:
      - 8082:80
    depends_on:
      - kafka
      - redis

  process:
    build:
      dockerfile: Dockerfile
      context: .
    command: "./bin/process"
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
      - redis

  kafka:
    image: docker.io/bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9093:9092
    depends_on:
      - zookeeper
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 4

  redis:
    image: redis:6.0
    ports:
      - 6379:6379

  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2182:2181
